// Import Express.
const express = require('express');
// Import path module.
const path = require('path');
// Create new instance of express.
const app = express();
// Set post where server will listen.
const PORT = process.env.PORT || 3000;
// Setup node fetch
const fetch = require('node-fetch');
// Set up cors
const cors = require('cors');
// Set up environment variables
require('dotenv').config();
// Set up middleware
app
  .use(express.json())
  .use(express.urlencoded({ extended: true }))
  .use(express.static(path.join(__dirname, 'public')))
  .use(cors({
    origin: 'http://127.0.0.1:5501'
  }))
// Get route for API deals
app.get('/deals', (req, res) => {
const cheapSharkUrl = 'https://www.cheapshark.com/api/1.0/deals?storeID=1&sortBy=Metacritic&desc=0&onSale=1&pageSize=3';
fetch(cheapSharkUrl)
    .then(response => response.json())
    .then(data => {
      let titlesThatNeedImages = makeTitlesArray(data);
      console.log(titlesThatNeedImages);
      let urlsGenerated = generateRawgUrls(titlesThatNeedImages);
      console.log(urlsGenerated);
      getRawgImageUrl(urlsGenerated);
      // addRawgSrc();
      res.json(data); // Send data back to frontend
    })
    .catch(error => {
      console.error('Error:', error);
      res.status(!200).send(error);;
    });
});
// Test rawg response.
app.get('/rawg', (req, res) => {
const rawgUrl = `https://api.rawg.io/api/games?search=The%20Witcher%203%3A%20Wild%20Hunt&key=${process.env.RAWG_API_KEY}`;
fetch(rawgUrl)
    .then(response => response.json())
    .then(data => {
      res.json(data);
    })
    .catch(error => {
      console.error('Error:', error);
      res.status(!200).send(error);;
    });
});
// For each game on sale returned by the cheapshark API, push the title into an array.
function makeTitlesArray(data) {
  let titleArray=[];
  data.forEach(objectInArray => {
    titleArray.push(objectInArray.title);
  });
  return titleArray;
}
// For each title, generate a url that will be used to make a request to the RAWG API for that specific title. 
function generateRawgUrls(titlesThatNeedImages) {
  let rawgUrlArray = []
  titlesThatNeedImages.forEach(titleInArray => {
    let encodedTitle = encodeURIComponent(titleInArray);
    console.log(encodedTitle);
    let rawgUrl = `https://api.rawg.io/api/games?search=${encodedTitle}&key=${process.env.RAWG_API_KEY}`;
    console.log(rawgUrl);
    rawgUrlArray.push(rawgUrl);
  });
  return rawgUrlArray;
}
// Make multiple simultaneous fetch requests using the urls generated by generateRawgUrls.  
// function getRawgImageUrl(urlsGenerated) {
//   let rawgImageUrlArray = []
//   urlsGenerated.forEach(urlInArray => {
//     console.log(urlInArray);
//     fetch(urlInArray)
//       .then(response => response.json())
//       .then(data => {
//           rawgImageUrlArray.push(data.results[0].background_image);
//       })
//       .catch(error => {
//         console.error('Error:', error);
//         res.status(!200).send(error);
//       });
//   });
//   console.log(rawgImageUrlArray);
//   return rawgImageUrlArray;
//// }
// Set up express server.
app.listen(PORT, () => console.log(`Now listening on ${PORT}`));
